In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
df=pd.read_csv("StudentsPerformance.csv")

In [ ]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
df.rename(columns={'parental level of education': 'parental_level_of_education'}, inplace=True)
df.rename(columns={'test preparation course': 'test_preparation_course'}, inplace=True)
df.rename(columns={'math score': 'math_score'}, inplace=True)
df.rename(columns={'reading score': 'reading_score'}, inplace=True)
df.rename(columns={'writing score': 'writing_score'}, inplace=True)

In [ ]:
df

,gender,race/ethnicity,parental_level_of_education,lunch,test_preparation_course,math_score,reading_score,writing_score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [ ]:
# unwanted coloumns are removed
df.drop(columns=['lunch'], inplace=True)

In [ ]:
df.describe

<bound method NDFrame.describe of      gender race/ethnicity parental_level_of_education  \
0    female        group B           bachelor's degree
1    female        group C                some college
2    female        group B             master's degree
3      male        group A          associate's degree
4      male        group C                some college
..      ...            ...                         ...
995  female        group E             master's degree
996    male        group C                 high school
997  female        group C                 high school
998  female        group D                some college
999  female        group D                some college

    test_preparation_course  math_score  reading_score  writing_score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 7 columns]>

In [ ]:
# searchig for missing vakues if there are any
df.isna().any()

gender                         False
race/ethnicity                 False
parental_level_of_education    False
test_preparation_course        False
math_score                     False
reading_score                  False
writing_score                  False
dtype: bool

In [ ]:
df.to_csv("Student_CleanData.csv")